
List<String> mames = [
  'Riley',
  'Reyna',
  'Lashunda',
  'Ismael',
  'Pearly',
  'Quinton',
  'Terry',
  'Donette',
  'Francoise',
  'Shelba',
  'Amber',
  'Velma',
  'Keturah',
  'Thanh',
  'Bertram',
  'Roosevelt',
  'Clementina',
  'Cristobal',
  'Earlie',
  'Cora',
  'Pearle',
  'Kirstin',
  'Alfred',
  'Richard',
  'Arica',
  'Vannessa',
  'Carlyn',
  'Melody',
  'Edgardo',
  'Elden',
  'Broderick',
  'Sharilyn',
  'Santo',
  'Jerrell',
  'Elliott',
  'Shon',
  'Daisy',
  'Evangelina',
  'Malka',
  'Ernestine',
  'Williams',
  'Jannet',
  'Jerrod',
  'Grady',
  'Lanell',
  'Lana',
  'Skye',
  'Janett',
  'Angelyn',
  'Donte'
];
List<String> lastName = [
  'Randall',
  'Rees',
  'Reid',
  'Roberts',
  'Robertson',
  'Ross',
  'Russell',
  'Rutherford',
  'Sanderson',
  'Scott',
  'Sharp',
  'Short',
  'Simpson',
  'Skinner',
  'Slater',
  'Smith',
  'Springer',
  'Stewart',
  'Sutherland',
  'Taylor',
  'Terry',
  'Thomson',
  'Tucker',
  'Turner',
  'Underwood',
  'Vance',
  'Vaughan',
  'Walker',
  'Wallace',
  'Walsh',
  'Watson',
  'Welch',
  'White',
  'Wilkins',
  'Wilson',
  'Wright',
  'Young',
];

List<String> comments = [
  'I can\'t get over how different the weather is here.',
  'He apologized for his rudeness, but she wouldn\'t forgive him.',
  'We need more workers.',
  'She was asked not to speak at the meeting.',
  'We walked ten miles that day.',
  'She advised him to walk instead of taking a bus but she didnt agree',
  'We all laughed at his pink tuxedo.',
  'The blue SUV in front of the Honda.',
  'There is an urgent need for improved living conditions.',
  'She sold all of her furniture, so she could afford to feed herself and her dog.'
];
